import { ITariff } from "../models/tariff.model";

export const tariffData: ITariff[] = [
  {
    id: 0,
    name: 'Tarrif A',
    download: 15,
    upload: 7,
    price: '123.45',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 1,
    name: 'Tarrif B',
    download: 12,
    upload: 6,
    price: '120.00',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 2,
    name: 'Tarrif C',
    download: 18,
    upload: 8,
    price: '130.50',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 3,
    name: 'Tarrif D',
    download: 30,
    upload: 10,
    price: '150.45',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 4,
    name: 'Tarrif E',
    download: 10,
    upload: 5,
    price: '118.50',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 5,
    name: 'Tarrif F',
    download: 10,
    upload: 5,
    price: '118.50',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 6,
    name: 'Tarrif G',
    download: 10,
    upload: 5,
    price: '118.50',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 7,
    name: 'Tarrif H',
    download: 10,
    upload: 5,
    price: '118.50',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 8,
    name: 'Tarrif I',
    download: 10,
    upload: 5,
    price: '118.50',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
  {
    id: 9,
    name: 'Tarrif J',
    download: 10,
    upload: 5,
    price: '118.50',
    benefits: ['Benefit-1', 'Benefit-2', 'Benefit-3', 'Benefit-4'],
    tariffFeatures: '',
  },
];
